import "./globals.scss";

export const metadata = {
  title: "Next.js 연습",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <h1 className="title">오늘 점심 머먹?</h1>
        {children}
        <div className="title-sub">by hole shin</div>
      </body>
    </html>
  );
}
