import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js 연습",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
